### PR TITLE
T/ckeditor5/1636

### LINKED ISSUE #3: Add indent/outdent icons for the buttons
The indent/outdent buttons are missing icons.

### LINKED ISSUE #5: Using em for indentation causes visually incorrect behaviour when font sizes differ
image

CKEditor 4 uses 40px step, so perhaps we should switch to that.

### LINKED ISSUE #2354: Using em for indentation causes visually incorrect behaviour when font sizes differ
image

CKEditor 4 uses 40px step, so perhaps we should switch to that.

### LINKED ISSUE #2356: Add indent/outdent icons for the buttons
The indent/outdent buttons are missing icons.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Implement Indent and IndentBlock features. Closes ckeditor/ckeditor5#2356. Closes ckeditor/ckeditor5#2354.

---

### Additional information

This is part of [IndentBlock PR](https://github.com/ckeditor/ckeditor5/pull/1816).

### CODE REVIEW

File: src/indentcommandbehavior/indentusingclasses.js [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+		 * The direction of indentation.
+		 *
+		 * @type {Boolean}
+		 */
+		this.isForward = config.direction === 'forward';
+
+		/**
+		 * List of classes used for indentation.
+		 *
+		 * @type {Array<String>}
```
Comment (Reinmar) [inline src/indentcommandbehavior/indentusingclasses.js]:
```suggestion
		 * @type {Array.<String>}
```

File: src/indentblock.js [hunk 2]
```diff
@@ -0,0 +1,289 @@
...
+	/**
+	 * @inheritDoc
+	 */
+	init() {
+		const editor = this.editor;
+		const schema = editor.model.schema;
+		const conversion = editor.conversion;
+		const configuration = editor.config.get( 'indentBlock' );
+
+		// TODO: supported in CKE4:
```
Comment (Reinmar) [inline src/indentblock.js]: I think it's fine what we have for now. We can document how to enable indent on other elements (which is done by the extending the schema, so it's pretty straightforward).

File: src/indentblock.js [hunk 3]
```diff
@@ -0,0 +1,289 @@
...
+				const command = this.editor.commands.get( commandName );
+
+				if ( command.isEnabled ) {
+					this.editor.execute( commandName );
+					cancel();
+				}
+			};
+		};
+
+		editor.keystrokes.set( 'Tab', getCommandExecuter( 'indentBlock' ) );
```
Comment (Reinmar) [inline src/indentblock.js]: <kbd>Tab</kbd> should only work in lists. For a11y reasons, by default, it should leave the editor. So this code should be removed.

File: src/indentblock.js [hunk 4]
```diff
@@ -0,0 +1,289 @@
...
+				}
+			},
+			model: {
+				key: 'blockIndent',
+				value: viewElement => viewElement.getStyle( 'margin-left' )
+			}
+		} );
+
+		// The margin shorthand should also work.
+		conversion.for( 'upcast' ).attributeToAttribute( {
```
Comment (Reinmar) [inline src/indentblock.js:113]: We talked that style normalization should work on element/consumable level (so, be completely automatic), but if this works already, we can keep it.

File: src/indentblockcommand.js [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+ *
+ * @method #checkEnabled
+ * @param {String} indentAttributeValue Current indent attribute value.
+ * @returns {Boolean}
+ */
+
+/**
+ * Returns new indent attribute value based on current indent.
+ *
+ * @method #getNewIndent
```
Comment (Reinmar) [inline src/indentblockcommand.js]: getNextIndent?

File: docs/features/indent-block.md [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+```
+
+Then add it to your plugin list and the toolbar configuration:
+
+```js
+import Font from '@ckeditor/ckeditor5-indent-block/src/indentblock';
+
+ClassicEditor
+	.create( document.querySelector( '#editor' ), {
+		plugins: [ IndentBlock, ... ],
```
Comment (Reinmar) [inline docs/features/indent-block.md]: Don't you also have to load the `Indent` plugin?
